name: Daily Build Meson Multi-Platform

on:
  schedule:
    - cron: '0 0 * * *'  # daily at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux targets
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-latest
            arch: i686
    name: Build ${{ matrix.os }}-${{ matrix.arch }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y build-essential meson ninja-build python3-pip xz-utils libreadline-dev
          if [ "${{ matrix.arch }}" = "i686" ]; then
              sudo apt install -y gcc-multilib g++-multilib
          fi

      - name: Configure build
        run: |
          mkdir -p build
          meson setup build --buildtype release

      - name: Build
        run: |
          meson compile -C build

      - name: Package
        run: |
          LATEST_TAG=$(git rev-parse --short HEAD)
          TODAY=$(date +%Y%m%d)
          TARGET="${{ matrix.os }}-${{ matrix.arch }}"
          mkdir -p dist
          tar -cJf dist/kzsh-${LATEST_TAG}-${TODAY}-${TARGET}.tar.xz -C build .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kzsh-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/kzsh-*.tar.xz
