name: Daily Build Meson Linux

on:
  schedule:
    - cron: '0 0 * * *'  # daily at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: x86_64
          - arch: i686
    name: Build Linux-${{ matrix.arch }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential meson ninja-build python3-pip xz-utils
          if [ "${{ matrix.arch }}" = "i686" ]; then
              sudo apt install -y gcc-multilib g++-multilib
          fi

      - name: Configure build
        run: |
          mkdir -p build
          if [ "${{ matrix.arch }}" = "i686" ]; then
              # 32-bit build
              CC="gcc -m32" CXX="g++ -m32" meson setup build --buildtype release
          else
              meson setup build --buildtype release
          fi

      - name: Build
        run: meson compile -C build

      - name: Package
        run: |
          COMMIT=$(git rev-parse --short HEAD)
          TODAY=$(date +%Y%m%d)
          TARGET="linux-${{ matrix.arch }}"
          mkdir -p dist
          tar -cJf dist/kzsh-${COMMIT}-${TODAY}-${TARGET}.tar.xz -C build .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kzsh-linux-${{ matrix.arch }}
          path: dist/kzsh-*.tar.xz
